
export ZSH="$HOME/.oh-my-zsh"

export NVM_DIR="$HOME/.nvm"

export HOMEBREW_CASK_OPTS="--no-quarantine --no-binaries"

export PATH="$PATH:/Users/oysteinm/Tools/flutter/bin"

export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"

export KEYTIMEOUT=1

. "$HOME/.cargo/env"

function exists() {
    command -v $1 >/dev/null 2>&1
}
