
export ZSH="$HOME/.oh-my-zsh"

export NVM_DIR="$HOME/.nvm"

export HOMEBREW_CASK_OPTS="--no-quarantine --no-binaries"

export PATH="$PATH:/Users/oysteinm/Tools/flutter/bin"

export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"

export PATH="$HOME/.cargo/bin:$PATH"

export KEYTIMEOUT=1

export FZF_ALT_C_COMMAND="fd -t d . $HOME/Developer --exclude .git \
                          --exclude node_modules --exclude target --maxdepth 3"

export function exists() {
    command -v $1 >/dev/null 2>&1
}

export function take() {
  mkdir -p $1
  cd $1
}

