
plugins=(
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf-tab
  you-should-use
  )

source $ZSH/oh-my-zsh.sh

[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

unalias -m '*'
source ~/.aliases

bindkey -v

eval "$(zoxide init zsh)"
eval "$(atuin init zsh)"
eval "$(starship init zsh)"
