plugins=(
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf-tab
  you-should-use
  )

source $ZSH/oh-my-zsh.sh
source $(brew --prefix nvm)/nvm.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

unalias -m '*'
source ~/.aliases

bindkey -v
bindkey "ç" fzf-cd-widget

eval "$(zoxide init zsh)"
eval "$(atuin init zsh)"
eval "$(starship init zsh)"
