return {
    { "akinsho/bufferline.nvim",      enabled = false },
    { "nvim-neo-tree/neo-tree.nvim",  enabled = false },
    { "echasnovski/mini.ai",          enabled = false },
    { "echasnovski/mini.indentscope", enabled = false },
    { "echasnovski/mini.surround",    enabled = false },
    { "stevearc/dressing.nvim",       enabled = false },
    { "rcarriga/nvim-notify",         enabled = false },
    { "folke/persistence.nvim",       enabled = false },
    { "windwp/nvim-spectre",          enabled = false },
    { "ggandor/flit.nvim",            enabled = false },
    { "ggandor/leap.nvim",            enabled = false },
    { "folke/noice.nvim",             enabled = false },
    { "tpope/vim-repeat",             enabled = false },
    { "RRethy/vim-illuminate",        enabled = false },
    { "echasnovski/mini.pairs",       enabled = false },
    { "lewis6991/gitsigns.nvim",      enabled = false },
}
